GET http://localhost:8002/business/hello
Accept: application/json

###

GET http://localhost:8002/business/admin/train/query-all
Accept: application/json

###

GET http://localhost:8002/business/admin/station/query-all
Accept: application/json

###