POST http://localhost:8001/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "name": "list",
  "idCard": "123123",
  "type": "2"
}

###

POST http://localhost:8001/member/passenger/save
Content-Type: application/json
token: {{token}}

{
  "id": 1726848580230189056,
  "memberId": 1,
  "name": "ccen",
  "idCard": "123456789",
  "type": "1"
}

###

GET http://localhost:8001/member/passenger/query-list?page=1&size=2
Accept: application/json
token: {{token}}

###