server:
  port: 8000

spring:
  cloud:
    gateway:
      routes[0]:
        id: member
        uri: http://127.0.0.1:8001
        predicates:
          - Path=/member/**
      routes[1]:
        id: business
        uri: http://127.0.0.1:8002
        predicates:
          - Path=/business/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedHeaders: '*'
            allowedMethods: '*'
            allowedOriginPatterns: '*'
            maxAge: 3600